var deals = [
{
      "type": "online booking available",
      "id": 301,
      "lat": 52.52353261403368,
      "lon": 13.329849243164062,
      "tags": {
        "name": "Upside Down Museum",
        "image": "img/panagea/tour_b13.jpg",
        "imagesmall": "img/panagea/pois/tour_b13.jpg",
        "description": "A chilly museum for all ages where everything is up side down. Huge fun included..",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 22,
		"chrate": 17
      }
},
{
      "type": "online booking available",
      "id": 302,
      "lat": 52.53627304145948,
      "lon": 13.406753540039062,
      "tags": {
        "name": "TV tower Panaroma Tour",
        "image": "img/panagea/tour_a5.jpg",
        "imagesmall": "img/panagea/pois/tour_a5.jpg",
        "description": "Fascinating city panaroma is awaiting to be explored. Including guided tour of the television tower.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 18,
		"chrate": 12
      }
},
{
      "type": "online booking available",
      "id": 303,
      "lat": 52.538465693007474,
      "lon": 13.372249603271484,
      "tags": {
        "name": "Discover the football stadium",
        "image": "img/panagea/tour_b11.jpg",
        "imagesmall": "img/panagea/pois/tour_b11.jpg",
        "description": "Discover the city's most famous football stadium. Including guided tour of the stadium.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 26,
		"chrate": 16
      }
},
{
      "type": "online booking available",
      "id": 304,
      "lat": 52.54723520421158,
      "lon": 13.326244354248047,
      "tags": {
        "name": "Discover castle and locks",
        "image": "img/panagea/tour_b12.jpg",
        "imagesmall": "img/panagea/pois/tour_b12.jpg",
        "description": "Advance sales for admission to the most popular castle and locks tour, with guide.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 25,
		"chrate": 16
      }
},
{
      "type": "online booking available",
      "id": 305,
      "lat": 52.51402710160184,
      "lon": 13.305301666259766,
      "tags": {
        "name": "Advance sales tickets for the city museum",
        "image": "img/panagea/tour_b15.jpg",
        "imagesmall": "img/panagea/pois/tour_b15.jpg",
        "description": "Advance sales for admission to the most popular museum in the city. Groups very welcome.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 16,
		"chrate": 9
      }
},
{
      "type": "online booking available",
      "id": 306,
      "lat": 52.50389258754797,
      "lon": 13.409671783447266,
      "tags": {
        "name": "Tour to the great castle rock",
        "image": "img/panagea/tour_c23.jpg",
        "imagesmall": "img/panagea/pois/tour_c23.jpg",
        "description": "Advance sales tickets for tour to the great castle rock. Groups very welcome.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 19,
		"chrate": 13
      }
},
{
      "type": "online booking available",
      "id": 307,
      "lat": 52.52478593472457,
      "lon": 13.462028503417969,
      "tags": {
        "name": "Planetarium tour with guide",
        "image": "img/panagea/tour_b17.jpg",
        "imagesmall": "img/panagea/pois/tour_b17.jpg",
        "description": "Advance sales tickets for the planetarium tour with guide. Groups very welcome.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 25,
		"chrate": 17
      }
},
{
      "type": "online booking available",
      "id": 308,
      "lat": 52.48905227994953,
      "lon": 13.467178344726562,
      "tags": {
        "name": "Garden show - world of flowers",
        "image": "img/panagea/tour_b19.jpg",
        "imagesmall": "img/panagea/pois/tour_b19.jpg",
        "description": "Advance sales tickets for the State Garden Show. Group entrance possible.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 17,
		"chrate": 9
      }
},
{
      "type": "online booking available",
      "id": 309,
      "lat": 52.50002622934633,
      "lon": 13.324871063232422,
      "tags": {
        "name": "Day long adventure Luna Park",
        "image": "img/panagea/tour_c24.jpg",
        "imagesmall": "img/panagea/pois/tour_c24.jpg",
        "description": "Early sales day ticket for Day long adventure Luna Park. Group entrance possible.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 29,
		"chrate": 19
      }
},
{
      "type": "online booking available",
      "id": 310,
      "lat": 52.507027222951635,
      "lon": 13.339977264404295,
      "tags": {
        "name": "Zoo & Wild park Adventure",
        "image": "img/panagea/tour_b18.jpg",
        "imagesmall": "img/panagea/pois/tour_b18.jpg",
        "description": "Presale day ticket for the Zoo & Wildpark. Groups very welcome.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 26,
		"chrate": 17
      }
},
{
      "type": "online booking available",
      "id": 311,
      "lat": 52.49093372292005,
      "lon": 13.329334259033201,
      "tags": {
        "name": "3D Art museum tour",
        "image": "img/panagea/tour_b16.jpg",
        "imagesmall": "img/panagea/pois/tour_b16.jpg",
        "description": "Presale day ticket for the 3D tour in the Kunst Museum. Groups very welcome.",
        "wheelchair": "yes",
        "opening_hours": "",
        "phone": "+49 30 11 2233",
		"adrate": 21,
		"chrate": 15
      }
}
];

var markers = [
{
      "type": "heritage",
      "id": 241490725,
      "lat": 52.4876488,
      "lon": 13.3814783,
      "tags": {
        "description": "Nationaldenkmal auf dem Kreuzberg",
        "heritage": "4",
        "heritage:operator": "lda",
        "historic": "monument",
        "image": "img/panagea/pois/Kreuzberg_Berlin_Nationaldenkmal_2.jpg",
        "lda:criteria": "Baudenkmal",
        "memorial": "war_memorial",
        "memorial:conflict": "Napoleonic_Wars",
        "name": "Nationaldenkmal für die Befreiungskriege",
        "ref:lda": "09031258",
        "wikidata": "Q819820",
        "wikimedia_commons": "Category:Nationaldenkmal auf dem Kreuzberg (Berlin)",
        "wikipedia": "de:Nationaldenkmal für die Befreiungskriege"
      }
    },
    {
      "type": "heritage",
      "id": 262455591,
      "lat": 52.517253,
      "lon": 13.3927431,
      "tags": {
        "artist_name": "Christian Daniel Rauch",
        "artwork_type": "statue",
        "heritage": "4",
        "heritage:operator": "lda",
        "historic": "statue",
        "image": "img/panagea/pois/Berlin_Mitte_Unter_den_Linden_Reiterstandbild_Friedrich_II.jpg",
        "image:0": "https://photos.app.goo.gl/rcLuAwB1XNwfmhGD7",
        "lda:criteria": "Baudenkmal",
        "name": "Reiterstandbild Friedrich II. von Preußen",
        "name:de": "Reiterstandbild Friedrich II. von Preußen",
        "name:el": "ΕΦΙΠΠΟΣ ΑΝΔΡΙΑΝΤΑΣ ΤΟΥ ΜΕΓΓΑΛΟΥ ΦΡΕΙΔΕΡΙΚΟΥ",
        "name:en": "Frederick II of Prussia",
        "name:fr": "Frédéric II de Prusse",
        "name:he": "פרידריך השני, מלך פרוסיה",
        "name:lb": "Friedrich II. vu Preisen",
        "name:lt": "Frydrichas II iš Prūsijos",
        "name:ru": "Фридрих II",
        "name:zh": "腓特烈二世",
        "ref:lda": "09060118",
        "statue": "equestrian",
        "tourism": "artwork",
        "wheelchair": "yes",
        "wikidata": "Q881611",
        "wikimedia_commons": "Category:Reiterstandbild Friedrichs des Großen (Berlin-Mitte)",
        "wikipedia": "de:Reiterstandbild Friedrichs des Großen"
      }
    },
    {
      "type": "heritage",
      "id": 262457570,
      "lat": 52.5136361,
      "lon": 13.3926475,
      "tags": {
        "artist:wikidata": "Q603105",
        "artist:wikipedia": "Reinhold_Begas",
        "artist_name": "Reinhold Begas",
        "commemorates:wikidata": "Q22670",
        "direction": "E",
        "heritage": "4",
        "heritage:operator": "lda",
        "historic": "memorial",
        "image": "img/panagea/pois/Schillerdenkmal_Berlin_Gendarmenmarkt_Begas_1.jpg",
        "lda:criteria": "Baudenkmal",
        "memorial": "statue",
        "name": "Schiller-Denkmal",
        "name:de": "Schiller-Denkmal",
        "name:en": "Schiller Monument",
        "name:ru": "Памятник Шиллеру",
        "ref:lda": "09060093",
        "wheelchair": "yes",
        "wikidata": "Q1295061",
        "wikimedia_commons": "Category:Schillerdenkmal (Gendarmenmarkt)",
        "wikipedia": "de:Schiller-Denkmal (Berlin)"
      }
    },
    {
      "type": "heritage",
      "id": 376689138,
      "lat": 52.5190984,
      "lon": 13.3991493,
      "tags": {
        "architect": "Johann Gottlieb Christian Cantian",
        "artist_name": "Christian Gottlieb Cantian",
        "heritage": "4",
        "heritage:operator": "lda",
        "heritage:website": "https://denkmaldatenbank.berlin.de/daobj.php?obj_dok_nr=09012501",
        "image": "img/panagea/pois/20230729_1528202.jpg",
        "lda:criteria": "Baudenkmal",
        "loc_name": "Berliner Suppenschüssel",
        "name": "Granitschale im Lustgarten",
        "ref:lda": "09012501",
        "start_date": "1827..1834",
        "tourism": "artwork",
        "wheelchair": "yes",
        "wikidata": "Q1543108",
        "wikimedia_commons": "Category:Granite bowl (Lustgarten Berlin)",
        "wikipedia": "de:Granitschale im Lustgarten"
      }
    },
    {
      "type": "heritage",
      "id": 437319063,
      "lat": 52.5176016,
      "lon": 13.3934583,
      "tags": {
        "direction": "S",
        "heritage": "4",
        "heritage:operator": "lda",
        "historic": "memorial",
        "image": "img/panagea/pois/Statue_Unter_den_Linden_6_(Mitte)_Wilhelm_von_Humboldt.jpg",
        "image:0": "https://photos.app.goo.gl/LE7e77wsHg1QjmcU6",
        "lda:criteria": "Baudenkmal",
        "memorial": "statue",
        "name": "Wilhelm von Humboldt",
        "name:be": "Вільгельм Гумбальдт",
        "ref:lda": "09060127",
        "tourism": "artwork",
        "wheelchair": "no",
        "wikidata": "Q24976694",
        "wikimedia_commons": "Category:Statue of Wilhelm von Humboldt, Berlin",
        "wikipedia": "de:Wilhelm-von-Humboldt-Denkmal (Berlin)"
      }
    },
    {
      "type": "heritage",
      "id": 437319127,
      "lat": 52.5176423,
      "lon": 13.3940809,
      "tags": {
        "direction": "S",
        "heritage": "4",
        "heritage:operator": "lda",
        "historic": "memorial",
        "image": "img/panagea/pois/Humboldt_Alexander.jpg",
        "image:0": "https://photos.app.goo.gl/5GShYhoAjLBCa5VN6",
        "lda:criteria": "Baudenkmal",
        "memorial": "statue",
        "name": "Alexander von Humboldt",
        "name:be": "Аляксандр Гумбальдт",
        "name:de": "Alexander von Humboldt",
        "name:lt": "Aleksanderis fon Humboltas",
        "ref:lda": "09060120",
        "tourism": "artwork",
        "wheelchair": "no",
        "wikidata": "Q17351109",
        "wikimedia_commons": "Category:Statue of Alexander von Humboldt, Berlin",
        "wikipedia": "de:Alexander-von-Humboldt-Denkmal (Berlin)"
      }
    },
    {
      "type": "heritage",
      "id": 667211397,
      "lat": 52.5163909,
      "lon": 13.2605451,
      "tags": {
        "artist_name": "Louis Tuaillon",
        "artwork_type": "sculpture",
        "heritage": "4",
        "heritage:operator": "lda",
        "image": "img/panagea/pois/Stuebenplaz_der_Sieger.jpg",
        "lda:criteria": "Baudenkmal",
        "name": "Der Sieger",
        "ref:lda": "09096447",
        "tourism": "artwork",
        "wikidata": "Q61767684"
      }
    },
    {
      "type": "heritage",
      "id": 966899245,
      "lat": 52.4873589,
      "lon": 13.4139617,
      "tags": {
        "architect": "Katharina Szelinski-Singer",
        "construction_year": "1955",
        "description": "Plastik, Denkmal und Gedenkstein",
        "heritage": "4",
        "heritage:operator": "lda",
        "heritage:website": "https://denkmaldatenbank.berlin.de/daobj.php?obj_dok_nr=09097455",
        "historic": "memorial",
        "image": "img/panagea/pois/09097455.jpg",
        "inscription": "IN DANKBARKEIT DEN BERLINERINNEN GEWIDTMET DIE NACH DEM 2. WELTKRIEG ALS »TRÜMMERFRAUEN« DIE TRÜMMER DER ZERSTÖRTEN STADT BESEITIGTEN UND DAMIT IHREN WIEDERAUFBAU BEGRÜNDETEN",
        "lda:criteria": "Baudenkmal",
        "memorial": "statue",
        "name": "Trümmerfrau-Denkmal",
        "ref:lda": "09097455",
        "start_date": "1955",
        "wheelchair": "yes",
        "wikidata": "Q2457242",
        "wikimedia_commons": "Category:Trümmerfrau-Denkmal (Berlin-Neukölln)",
        "wikipedia": "de:Trümmerfrau-Denkmal (Berlin-Neukölln)"
      }
    },
    {
      "type": "heritage",
      "id": 3058015348,
      "lat": 52.5178141,
      "lon": 13.3932623,
      "tags": {
        "heritage": "4",
        "heritage:operator": "lda",
        "historic": "memorial",
        "image": "img/panagea/pois/20230729_1536252.jpg",
        "lda:criteria": "Baudenkmal",
        "memorial": "statue",
        "name": "Theodor Mommsen",
        "ref:lda": "09060117",
        "wheelchair": "yes",
        "wikidata": "Q24976703",
        "wikimedia_commons": "Category:Denkmal Theodor Mommsen (Berlin)",
        "wikipedia": "en:Statue of Theodor Mommsen"
      }
    },
    {
      "type": "heritage",
      "id": 3058015349,
      "lat": 52.5178477,
      "lon": 13.3937304,
      "tags": {
        "heritage": "4",
        "heritage:operator": "lda",
        "historic": "memorial",
        "image": "img/panagea/pois/20230729_1533222.jpg",
        "lda:criteria": "Baudenkmal",
        "memorial": "statue",
        "name": "Hermann von Helmholtz",
        "ref:lda": "09060116",
        "wheelchair": "yes",
        "wikidata": "Q24976702",
        "wikimedia_commons": "Category:Statue Hermann von Helmholtz (Berlin)",
        "wikipedia": "en:Statue of Hermann von Helmholtz"
      }
    },
    {
      "type": "heritage",
      "id": 3513338377,
      "lat": 52.5130495,
      "lon": 13.4153741,
      "tags": {
        "artist:wikidata": "Q51989",
        "artist_name": "Johann Gottfried Schadow",
        "artwork_type": "statue",
        "heritage": "4",
        "heritage:operator": "lda",
        "image": "img/panagea/pois/Berlin,_Mitte,_Köllnischer_Park,_Herkules_im_Kampf_mit_dem_Nemeischen_Löwen,_Schadow_und_Boy.jpg",
        "lda:criteria": "Ensembleteil",
        "material": "sandstone",
        "name": "Herkules im Kampf mit dem Nemeischen Löwen",
        "start_date": "1791",
        "tourism": "artwork",
        "wheelchair": "yes",
        "wikidata": "Q26703182",
        "wikimedia_commons": "Category:Herkules im Kampf mit dem Nemëischen Löwen (Conrad Nicolaus Boy after Johann Gottfried Schadow)",
        "wikipedia": "de:Köllnischer Park#Lapidarium"
      }
    },
    {
      "type": "heritage",
      "id": 5364256424,
      "lat": 52.523047,
      "lon": 13.3990679,
      "tags": {
        "architect": "Julius Moser",
        "architect:wikidata": "Q1520252",
        "heritage": "4",
        "heritage:operator": "lda",
        "heritage:website": "https://denkmaldatenbank.berlin.de/daobj.php?obj_dok_nr=09060099",
        "historic": "memorial",
        "image": "img/panagea/pois/Büste_Adelbert_von_Chamisso_Julius_Moser_Monbijoupark_Berlin_01.jpg",
        "inscription": "CHAMISSO",
        "lda:criteria": "Baudenkmal",
        "material": "marble",
        "memorial": "bust",
        "name": "Chamisso",
        "ref:lda": "09060099",
        "start_date": "1888",
        "subject:wikidata": "Q154782",
        "wheelchair": "yes",
        "wikidata": "Q61769328",
        "wikimedia_commons": "Category:Büste Adelbert von Chamisso (Berlin)"
      }
    },
    {
      "type": "historic",
      "id": 262525336,
      "lat": 52.5165158,
      "lon": 13.3939369,
      "tags": {
        "historic": "memorial",
        "image": "img/panagea/pois/Bebelplatz_mit_Mahnmal_Bücherverbrennung_Aug_2009.jpg",
        "memorial": "plaque",
        "name": "Denkmal zur Erinnerung an die Bücherverbrennung",
        "name:de": "Denkmal zur Erinnerung an die Bücherverbrennung",
        "name:en": "Memorial for the Nazi book burnings",
        "name:it": "Memoriale per il rogo nazista dei libri",
        "name:lt": "Memorialas už Nacių knygų deginimus",
        "name:ru": "Пямятник сожжению книг",
        "wheelchair": "yes",
        "wikidata": "Q18191705",
        "wikimedia_commons": "Category:Book burning memorial on Bebelplatz",
        "wikipedia": "de:Denkmal zur Erinnerung an die Bücherverbrennung"
      }
    },
    {
      "type": "historic",
      "id": 270687313,
      "lat": 52.5158896,
      "lon": 13.3497493,
      "tags": {
        "artist_name": "Reinhold Begas",
        "historic": "memorial",
        "image": "img/panagea/pois/Bismarck-Nationaldenkmal.jpg",
        "image:0": "https://photos.app.goo.gl/zd1vxhdwYgsazEkw9",
        "material": "bronze",
        "memorial": "statue",
        "name": "Otto von Bismarck",
        "name:be": "Ота фон Бісмарк",
        "name:zh": "奥托·冯·俾斯麦像",
        "wheelchair": "yes",
        "wikidata": "Q679124",
        "wikipedia": "de:Bismarck-Nationaldenkmal (Berlin)"
      }
    },
    {
      "type": "historic",
      "id": 276945671,
      "lat": 52.5089257,
      "lon": 13.3433631,
      "tags": {
        "artist_name": "Ralf Schüler, Ursulina Schüler-Witte",
        "description": "An dieser Stelle wurde Rosa Luxemburgs Leichnam am 15.01.1919 in den Landwehrkanal geworfen.",
        "direction": "24",
        "historic": "memorial",
        "image": "img/panagea/pois/RosaLuxemburg2a.jpg",
        "image:0": "https://photos.app.goo.gl/kHoWkPjmVw7PSgSD6",
        "inscription": "Rosa Luxemburg",
        "material": "bronze",
        "memorial": "plaque",
        "name": "Rosa-Luxemburg-Denkmal",
        "wheelchair": "yes",
        "wikidata": "Q96338872",
        "wikimedia_commons": "Category:Rosa Luxemburg memorial (Berlin-Tiergarten)"
      }
    },
    {
      "type": "historic",
      "id": 278706862,
      "lat": 52.5154443,
      "lon": 13.350644,
      "tags": {
        "artist_name": "Joseph Uphues",
        "historic": "memorial",
        "image": "img/panagea/pois/Joseph_Uphues-Moltke-Berlin-Mutter_Erde_fec.jpg",
        "image:0": "https://photos.app.goo.gl/mvJoD7Q4QZZ6sXGA6",
        "material": "marble",
        "memorial": "statue",
        "name": "Helmuth Karl Bernhard von Moltke",
        "wheelchair": "yes",
        "wikidata": "Q24976693",
        "wikimedia_commons": "Category:Moltke-Denkmal (Berlin-Tiergarten)",
        "wikipedia": "de:Moltke-Denkmal (Berlin)"
      }
    },
    {
      "type": "historic",
      "id": 278738513,
      "lat": 52.5137982,
      "lon": 13.3763737,
      "tags": {
        "artist_name": "Fritz Schaper",
        "historic": "memorial",
        "image": "img/panagea/pois/Schaper_Goethe_1880,_Statue.jpg",
        "material": "marble",
        "memorial": "statue",
        "name": "Johann Wolfgang von Goethe",
        "wheelchair": "yes",
        "wikidata": "Q1534095",
        "wikipedia": "de:Goethe-Denkmal (Berlin)"
      }
    },
    {
      "type": "historic",
      "id": 300537920,
      "lat": 52.5260248,
      "lon": 13.4297346,
      "tags": {
        "historic": "memorial",
        "image": "img/panagea/pois/Fritz_Cremer_Spanien_1.jpg",
        "memorial": "war_memorial",
        "name": "Gedenkstätte für die Interbrigadisten im Spanischen Bürgerkrieg",
        "name:de": "Gedenkstätte für die Interbrigadisten im Spanischen Bürgerkrieg",
        "name:en": "Memorial for the International Brigades in the Spanish Civil War",
        "name:fr": "Mémorial des Brigades internationales de la guerre civile Espagnole",
        "subject:wikidata": "Q132518",
        "subject:wikipedia": "de:Spanienkämpfer",
        "wheelchair": "yes",
        "wikidata": "Q96337435",
        "wikimedia_commons": "Category:Gedenkstätte der deutschen Interbrigadisten (Berlin-Friedrichshain)"
      }
    },
    {
      "type": "historic",
      "id": 437140233,
      "lat": 52.5184194,
      "lon": 13.3747951,
      "tags": {
        "country": "DE",
        "flag:name": "Germany",
        "flag:type": "national",
        "flag:wikidata": "Q48160",
        "height": "28.5",
        "historic": "memorial",
        "image": "img/panagea/pois/Reichstag_Südwestturm_IMG_2900_edit.jpg",
        "inscription": "DEUTSCHE EINHEIT 3. OKTOBER 1990",
        "lit": "yes",
        "man_made": "flagpole",
        "memorial": "sculpture",
        "name": "Fahne der Einheit",
        "name:ar": "علم الوحدة",
        "name:de": "Fahne der Einheit",
        "name:en": "Unity Flag",
        "name:fr": "Drapeau de l'unité",
        "name:nl": "Vlag der Eenheid",
        "start_date": "1990-10-03",
        "subject": "Germany",
        "subject:wikidata": "Q183",
        "wheelchair": "yes",
        "wikidata": "Q1392131",
        "wikimedia_commons": "Category:Flagge der Einheit (Berlin)",
        "wikipedia": "de:Fahne der Einheit"
      }
    },
    {
      "type": "historic",
      "id": 489762789,
      "lat": 52.5161302,
      "lon": 13.3714315,
      "tags": {
        "historic": "tank",
        "image": "img/panagea/pois/20230729_161034_exported_2907_1690842922560.jpg",
        "name": "T-34-200",
        "tank": "T-34",
        "wikidata": "Q112161165",
        "wikimedia_commons": "Category:T-34 Model 1943 tanks at the Soviet Cenotaph in Berlin-Tiergarten",
        "wikipedia": "de:T-34"
      }
    },
    {
      "type": "historic",
      "id": 597701075,
      "lat": 52.5358716,
      "lon": 13.3438847,
      "tags": {
        "artist_name": "Volkmar Haase",
        "historic": "memorial",
        "image": "img/panagea/pois/Moabit_AnderPutlitzbrücke_Mahnmal.jpg",
        "level": "1",
        "memorial": "sculpture",
        "name": "Mahnmal zur Erinnerung an die Deportation jüdischer Bürger",
        "start_date": "1987",
        "wheelchair": "yes",
        "wikidata": "Q1191632",
        "wikimedia_commons": "Category:Deportationsmahnmal Putlitzbrücke",
        "wikipedia": "de:Deportationsmahnmal Putlitzbrücke"
      }
    },
    {
      "type": "historic",
      "id": 1226265142,
      "lat": 52.5205351,
      "lon": 13.2957624,
      "tags": {
        "historic": "memorial",
        "image": "img/panagea/pois/Schloss_Charlottenburg_2005_286.jpg",
        "inscription": "DIVO FRIDERICO GUILELMO MAGNO S. R. I. ARCHIC. ET ELECT. BRANDENB. SUO PATRIAE EXERCITUUM PATRI OPT. MAX. INCLYTO QUUM lNCOMPARABILIS HEROS DUM VIXIT AMOR ORBIS AEQUE AC TERROR HOSTIUM EXTITISSET HOC PIETATIS ET GLOR. AETERNAE MONUM . L. M. Q. P. PRIMUS E",
        "material": "bronze",
        "memorial": "statue",
        "name": "Friedrich Wilhelm",
        "name:ja": "フリードリヒ・ヴィルヘルム1世騎馬像",
        "statue": "equestrian",
        "wheelchair": "limited",
        "wikidata": "Q21130084",
        "wikipedia": "de:Reiterstandbild des Großen Kurfürsten"
      }
    },
    {
      "type": "historic",
      "id": 1349816085,
      "lat": 52.5260327,
      "lon": 13.5068497,
      "tags": {
        "historic": "memorial",
        "image": "img/panagea/pois/Gedenktafel_Herzbergstr_79_(Liber)_Kapitulation.jpg",
        "inscription": "8. Mai 1945",
        "memorial": "obelisk",
        "name": "8. Mai 1945",
        "name:en": "8 May 1945",
        "name:nl": "8 mei 1945",
        "wheelchair": "limited",
        "wikidata": "Q122977914",
        "wikimedia_commons": "Category:Denkmal 8. Mai 1945 (Evangelisches Krankenhaus Königin Elisabeth Herzberge)"
      }
    },
    {
      "type": "historic",
      "id": 1467624135,
      "lat": 52.4749056,
      "lon": 13.3376155,
      "tags": {
        "addr:city": "Berlin",
        "addr:country": "DE",
        "addr:housenumber": "4",
        "addr:postcode": "12159",
        "addr:street": "Stierstraße",
        "addr:suburb": "Friedenau",
        "historic": "memorial",
        "image": "img/panagea/pois/Stolperstein_Stierstr_4_(Friedn)_Stanislaus_Graf_von_Nayhauss-Cormons.jpg",
        "inscription": "Hier wohnte Stanislaus Graf von Nayhauss-Cormons Jg. 1875 im Widerstand verhaftet 26.6.1933 von Gestapo ermordet in Breslau",
        "material": "bronze",
        "memorial": "stolperstein",
        "memorial:ref": "1184",
        "name": "Stanislaus Graf von Nayhauss-Cormons",
        "network": "Stolpersteine Berlin",
        "person:date_of_birth": "1875",
        "subject:wikidata": "Q20020594",
        "subject:wikipedia": "de:Stanislaus_von_Nayhauß",
        "survey:date": "2013-08-05",
        "website": "https://www.stolpersteine-berlin.de/biografie/1184",
        "wheelchair": "yes",
        "wikidata": "Q44200493"
      }
    },
    {
      "type": "historic",
      "id": 2267145406,
      "lat": 52.5228605,
      "lon": 13.3472535,
      "tags": {
        "historic": "memorial",
        "image": "img/panagea/pois/Büste_Kirchstr_13_(Moabi)_Albert_Einstein.jpg",
        "image:0": "https://photos.app.goo.gl/uhDCrVy8LvijxzNF9",
        "memorial": "bust",
        "name": "Albert Einstein",
        "website": "https://web.archive.org/web/20210131123447/https://spree-bogen.de/erinnerung/",
        "wheelchair": "yes",
        "wikidata": "Q116266909",
        "wikimedia_commons": "Category:Porträt Albert Einstein (Heinrich Drake)"
      }
    },
    {
      "type": "historic",
      "id": 3058015350,
      "lat": 52.5177915,
      "lon": 13.3940178,
      "tags": {
        "artist_name": "Anna Franziska Schwarzbach",
        "historic": "memorial",
        "image": "img/panagea/pois/20230729_1534332.jpg",
        "material": "bronze",
        "memorial": "statue",
        "name": "Lise Meitner",
        "start_date": "10.07.2014",
        "wheelchair": "yes",
        "wikidata": "Q107399685",
        "wikimedia_commons": "Category:Statue Lise Meitner (2014 by Anna Franziska Schwarzbach)"
      }
    },
    {
      "type": "historic",
      "id": 4784564100,
      "lat": 52.5202218,
      "lon": 13.4059552,
      "tags": {
        "artist_name": "Paul Martin Otto",
        "historic": "memorial",
        "image": "img/panagea/pois/20230729_1433592.jpg",
        "memorial": "statue",
        "name": "Lutherdenkmal",
        "start_date": "1895",
        "subject:wikidata": "Q9554",
        "wheelchair": "yes",
        "wikidata": "Q1877872",
        "wikimedia_commons": "Category:Lutherdenkmal (Berlin, Marienkirche)",
        "wikipedia": "de:Lutherdenkmal (Berlin, Marienkirche)"
      }
    },
    {
      "type": "historic",
      "id": 10840185721,
      "lat": 52.4830774,
      "lon": 13.3497681,
      "tags": {
        "artist:wikidata": "Q1611545",
        "name": "Kriegerdenkmal Hermann Hosaeus",
        "historic": "memorial",
        "image": "img/panagea/pois/Hosaeus-Schoeneberg-Mutter_Erde_fec.jpg",
        "material": "metal",
        "memorial": "statue",
        "start_date": "1930-11",
        "website": "https://bildhauerei-in-berlin.de/bildwerk/kriegerdenkmal-5655/",
        "wikidata": "Q110230588",
        "wikimedia_commons": "Category:Fallen soldier memorial (Berlin-Schöneberg)"
      }
    },
    {
      "type": "historic",
      "id": 12046299315,
      "lat": 52.5445079,
      "lon": 13.4423249,
      "tags": {
        "historic": "memorial",
        "image": "img/panagea/pois/alfons_levy_c_otfw.jpg",
        "inscription": "HIER WOHNTE\nALFONS LEVY\nJG. 1888\nDEPORTIERT 29.10.1941\nŁODZ\nERMORDET IN\nCHELMNO",
        "memorial": "stolperstein",
        "memorial:addr": "Greifswalder Straße 152, Berlin-Prenzlauer Berg",
        "name": "Alfons Levy",
        "website": "https://www.stolpersteine-berlin.de/en/greifswalder-str/152/alfons-levy-lewy",
        "wikidata": "Q109289572"
      }
    },
{
      "type": "museum",
      "id": 73696610,
      "lat": 52.5076051,
      "lon": 13.3629858,
      "tags": {
        "email": "sekretariat@gdw-berlin.de",
        "fee": "no",
        "image": "img/panagea/pois/Bendlerblock.jpg",
        "name": "Gedenkstätte Deutscher Widerstand",
        "name:en": "Memorial to the German Resistance",
        "name:fr": "Memorial de la Résistance Allemande",
        "name:ru": "Мемориал Немецкого Сопротивления",
        "opening_hours": "Mo-We,Fr 09:00-18:00; Th 09:00-20:00; Sa-Su 10:00-18:00",
        "phone": "+49 30 26995000",
        "tourism": "museum",
        "website": "https://www.gdw-berlin.de/",
        "wheelchair": "limited",
        "wikidata": "Q880798",
        "wikimedia_commons": "Category:Gedenkstätte Deutscher Widerstand",
        "wikipedia": "de:Gedenkstätte Deutscher Widerstand"
      }
    },
    {
      "type": "museum",
      "id": 260768839,
      "lat": 52.5096032,
      "lon": 13.37351,
      "tags": {
        "image": "img/panagea/pois/Loriot_Vicco_von_Bülow_Ausstellung_Filmmuseum_Berlin_2008.JPG",
		"addr:city": "Berlin",
        "addr:country": "DE",
        "addr:housenumber": "2",
        "addr:postcode": "10785",
        "addr:street": "Potsdamer Straße",
        "addr:suburb": "Tiergarten",
        "name": "Deutsche Kinemathek - Museum für Film und Fernsehen",
        "name:en": "Museum of Film and Television Berlin",
        "name:fr": "Musée du cinéma",
        "name:nl": "Duits Museum der Film en Televisie",
        "name:zh": "影視博物館",
        "opening_hours": "We,Fr-Mo 10:00-18:00; Th 10:00-20:00",
        "subject": "cinematography",
        "toilets:wheelchair": "yes",
        "tourism": "museum",
        "website": "https://www.deutsche-kinemathek.de/",
        "wheelchair": "yes",
        "wikidata": "Q568921",
        "wikipedia": "de:Filmmuseum Berlin"
      }
    },
    {
      "type": "museum",
      "id": 281391655,
      "lat": 52.5145073,
      "lon": 13.487485,
      "tags": {
        "image": "img/panagea/pois/Sede_Stasi_Museum.JPG",
		"addr:city": "Berlin",
        "addr:country": "DE",
        "addr:housenumber": "103",
        "addr:postcode": "10365",
        "addr:street": "Ruschestraße",
        "addr:suburb": "Lichtenberg",
        "alt_name": "Forschungs- und Gedenkstätte Normannenstraße",
        "contact:email": "info@stasimuseum.de",
        "contact:fax": "+49 30 55368-53",
        "contact:phone": "+49 30 55368-54",
        "contact:website": "https://www.stasimuseum.de/",
        "entrance": "main",
        "fee": "yes",
        "museum": "history",
        "name": "Stasimuseum",
        "name:de": "Stasimuseum",
        "name:en": "Stasi Museum",
        "name:nl": "Stasimuseum",
        "name:pl": "Muzeum Stasi w Berlinie",
        "name:zh": "史戴西博物館",
        "opening_hours": "Mo-Fr 10:00-18:00; Sa-Su 11:00-18:00",
        "operator": "ASTAK e.V.",
        "operator:type": "private_non_profit",
        "tourism": "museum",
        "wheelchair": "yes",
        "wheelchair:description": "Barrierefreier Zugang über den Seiteneingang, Fahrstuhl und rollstuhlgerechte Toilette vorhanden",
        "wikidata": "Q570472",
        "wikimedia_commons": "Category:Stasimuseum, Berlin",
        "wikipedia": "de:Forschungs- und Gedenkstätte Normannenstraße"
      }
    },
    {
      "type": "museum",
      "id": 292738889,
      "lat": 52.5099308,
      "lon": 13.3872552,
      "tags": {
        "image": "img/panagea/pois/Berlin_Museum_fuer_Kommunikation_asv2019-07.jpg",
        "addr:country": "DE",
        "addr:housenumber": "16",
        "addr:postcode": "10117",
        "addr:street": "Leipziger Straße",
        "addr:suburb": "Mitte",
        "check_date": "2023-10-21",
        "fee": "no",
        "internet_access": "wlan",
        "internet_access:fee": "customers",
        "name": "Museum für Kommunikation",
        "name:en": "Communication Museum Berlin",
        "name:nl": "Communicatiemuseum Berlijn",
        "name:ru": "Музей связи",
        "opening_hours": "Tu 09:00-20:00; We-Fr 09:00-17:00; Sa-Su 10:00-18:00; PH 10:00-18:00",
        "phone": "+49 30 202940",
        "toilets:wheelchair": "yes",
        "tourism": "museum",
        "website": "https://www.mfk-berlin.de/",
        "wheelchair": "yes",
        "wikidata": "Q1271054",
        "wikimedia_commons": "Category:Museum für Kommunikation Berlin",
        "wikipedia": "de:Museum für Kommunikation Berlin"
      }
    },
    {
      "type": "museum",
      "id": 340388625,
      "lat": 52.5087884,
      "lon": 13.378434,
      "tags": {
        "image": "img/panagea/pois/Deutschlandmuseum.jpg",
        "addr:country": "DE",
        "addr:housenumber": "7",
        "addr:postcode": "10117",
        "addr:street": "Leipziger Platz",
        "addr:suburb": "Mitte",
        "contact:phone": "+49 30 398200450",
        "contact:website": "https://www.deutschlandmuseum.de/",
        "fee": "yes",
        "museum": "history",
        "name": "Deutschlandmuseum",
        "opening_hours": "Mo-Su 10:00-20:00",
        "operator": "Betreibergesellschaft Deutschland Museum DM GmbH",
        "operator:type": "private",
        "start_date": "2023-06-17",
        "toilets:wheelchair": "yes",
        "tourism": "museum",
        "wheelchair": "yes",
        "wikidata": "Q120122369",
        "wikipedia": "de:Deutschlandmuseum"
      }
    },
    {
      "type": "museum",
      "id": 369037135,
      "lat": 52.5460206,
      "lon": 13.3479549,
      "tags": {
        "image": "img/panagea/pois/7b.jpg",
        "addr:housenumber": "21",
        "addr:postcode": "13353",
        "addr:street": "Brüsseler Straße",
        "contact:facebook": "antikriegsmuseum",
        "contact:instagram": "antikriegsmuseum_berlin",
        "email": "info@anti-kriegs-museum.de",
        "facebook": "https://www.facebook.com/antikriegsmuseum/",
        "fee": "no",
        "instagram": "https://www.instagram.com/antikriegsmuseum_berlin/",
        "name": "Anti-Kriegs-Museum",
        "name:en": "Anti War Museum",
        "name:nl": "Anti-oorlogmuseum",
        "name:ru": "Антивоенный музей",
        "opening_hours": "Mo-Su,PH 16:00-20:00",
        "operator": "Anti-Kriegs-Museum e.V.",
        "phone": "+49 30 45490110",
        "start_date": "1982",
        "tourism": "museum",
        "website": "https://anti-kriegs-museum.de/",
        "wheelchair": "limited",
        "wikidata": "Q1441078",
        "img_direct": "https://upload.wikimedia.org/wikipedia/commons/2/22/Berlin%2C_Mitte%2C_Unter_den_Linden%2C_Zeughaus_09.jpg",
        "img_file": "http://commons.wikimedia.org/wiki/File:Bendelerblock.jpg",
        "wikipedia": "de:Anti-Kriegs-Museum"
      }
    },
    {
      "type": "museum",
      "id": 429739550,
      "lat": 52.5219182,
      "lon": 13.3799981,
      "tags": {
        "image": "img/panagea/pois/Berlin_Mitte_Luisenstrasse_39_Mietshaus.jpg",
        "addr:country": "DE",
        "addr:housenumber": "39",
        "addr:postcode": "10117",
        "addr:street": "Luisenstraße",
        "addr:suburb": "Mitte",
        "contact:website": "https://iaaw.hu-berlin.de/seminar-fuer-ostasien-studien/japan/mori-ogai-gedenkstaette",
        "name": "Mori-Ôgai-Gedenkstätte",
        "tourism": "museum",
        "wikidata": "Q1441078",
        "wikipedia": "de:Mori-Ōgai-Gedenkstätte"
      }
    },
    {
      "type": "museum",
      "id": 498822384,
      "lat": 52.5478117,
      "lon": 13.3892456,
      "tags": {
        "image": "img/panagea/pois/Berliner_Unterwelten_e.V.jpg",
        "addr:country": "DE",
        "addr:housenumber": "105",
        "addr:postcode": "13355",
        "addr:street": "Brunnenstraße",
        "addr:suburb": "Gesundbrunnen",
        "contact:phone": "+49-30-49910517",
        "fee": "yes",
        "guided_tour": "only",
        "museum": "history",
        "name": "Berliner Unterwelten-Museum",
        "name:de": "Berliner Unterwelten-Museum",
        "name:en": "Berlin Underworlds Museum",
        "name:zh": "柏林地底世界",
        "operator": "Berliner Unterwelten e.V.",
        "tourism": "museum",
        "website": "https://berliner-unterwelten.de/",
        "wheelchair": "no",
        "wikidata": "Q821833"
      }
    },
    {
      "type": "museum",
      "id": 538692583,
      "lat": 52.5304903,
      "lon": 13.3791152,
      "tags": {
        "image": "img/panagea/pois/Museum_für_Naturkunde.jpg",
        "addr:country": "DE",
        "addr:housenumber": "43",
        "addr:postcode": "10115",
        "addr:street": "Invalidenstraße",
        "addr:suburb": "Mitte",
        "alt_name": "Naturkundemuseum",
        "blind:description:de": "Im Museum für Naturkunde gibt es Führungen für Blinde und Sehgeschädigte, siehe http://www.absv.de/freizeit/naturkunde.htm .",
        "check_date": "2024-06-16",
        "check_date:opening_hours": "2024-04-12",
        "contact:phone": "+49 30 20938591",
        "contact:website": "https://www.museumfuernaturkunde.berlin/",
        "fee": "yes",
        "internet_access": "wlan",
        "internet_access:fee": "no",
        "museum": "nature",
        "name": "Museum für Naturkunde",
        "name:de": "Museum für Naturkunde",
        "name:el": "ΜΟΥΣΕΙΟ ΦΥΣΙΚΗΣ ΙΣΤΟΡΙΑΣ",
        "name:en": "Natural History Museum",
        "name:es": "Museo de Historia Natural",
        "name:fr": "Musée d'histoire naturelle",
        "name:nl": "Natuurkundemuseum",
        "network": "Leibniz-Gemeinschaft",
        "opening_hours": "Tu-Fr 09:30-18:00; Sa,Su 10:00-18:00",
        "operator": "Leibniz-Institut für Evolutions- und Biodiversitätsforschung",
        "operator:type": "public",
        "payment:cash": "yes",
        "payment:credit_cards": "yes",
        "payment:debit_cards": "yes",
        "ref:isil": "DE-MUS-813712",
        "research_institution": "yes",
        "start_date": "1889-12-02",
        "toilets": "yes",
        "toilets:wheelchair": "yes",
        "tourism": "museum",
        "wheelchair": "yes",
        "wikidata": "Q233098",
        "wikipedia": "de:Museum für Naturkunde (Berlin)"
      }
    },
    {
      "type": "museum",
      "id": 2959465154,
      "lat": 52.5065947,
      "lon": 13.3306266,
      "tags": {
        "addr:city": "Berlin",
        "addr:country": "DE",
        "addr:housenumber": "22-24",
        "addr:postcode": "10623",
        "addr:street": "Hardenbergstraße",
        "contact:email": "info@co-berlin.org",
        "contact:facebook": "coberlinphoto",
        "contact:fax": "+49 30 2844416-19",
        "contact:flickr": "http://www.flickr.com/photos/co-berlin",
        "contact:google_plus": "https://plus.google.com/u/0/b/109130650692312419642/dashboard/overview",
        "contact:instagram": "coberlin",
        "contact:phone": "+49 30 2844416-62",
        "contact:twitter": "@coberlin",
        "contact:website": "https://www.co-berlin.org",
        "contact:youtube": "@COBerlinVideo",
        "fee": "yes",
        "image": "img/panagea/pois/C-O_Berlin_im_Amerika_Haus-2577.jpg",
        "name": "C/O Berlin",
        "opening_hours": "PH,Mo-Su 11:00-20:00",
        "operator": "C/O Berlin Foundation",
        "toilets:wheelchair": "yes",
        "tourism": "museum",
        "wheelchair": "yes",
        "wheelchair:description": "Schwerbehinderte (mindestens 50 v. H. MdE) zahlen den ermäßigten Eintrittspreis, Begleitpersonen erhalten freien Eintritt.",
        "wikidata": "Q1022620",
        "wikimedia_commons": "Category:C/O Berlin",
        "wikipedia": "de:C/O Berlin"
      }
    },
    {
      "type": "museum",
      "id": 3203167561,
      "lat": 52.5177477,
      "lon": 13.3970225,
      "tags": {
        "addr:city": "Berlin",
        "addr:country": "DE",
        "addr:housenumber": "2",
        "addr:postcode": "10117",
        "addr:street": "Unter den Linden",
        "addr:suburb": "Mitte",
        "alt_name": "Zeughaus",
        "charge": "8 EUR",
        "contact:phone": "+49 30 203040",
        "contact:website": "https://www.dhm.de/",
        "fee": "yes",
        "image": "img/panagea/pois/Berlin,_Mitte,_Unter_den_Linden,_Zeughaus_09.jpg",
        "museum": "history",
        "name": "Deutsches Historisches Museum",
        "name:da": "Det tyske historiske museum",
        "name:de": "Deutsches Historisches Museum",
        "name:en": "German Historical Museum",
        "name:es": "Museo Histórico Alemán",
        "name:fr": "Musée historique allemand",
        "name:it": "Museo storico tedesco",
        "name:nb": "Det tyske historiske museum",
        "name:ru": "Немецкий исторический музей",
        "name:zh-Hans": "德国历史博物馆",
        "name:zh-Hant": "德國歷史博物館",
        "opening_hours": "Mo-Su 10:00-18:00; Dec 24 off",
        "operator": "Stiftung Deutsches Historisches Museum",
        "operator:type": "public",
        "short_name": "DHM",
        "start_date": "1987-10-28",
        "toilets:wheelchair": "yes",
        "tourism": "museum",
        "wheelchair": "yes",
        "wikidata": "Q688335",
        "wikipedia": "de:Deutsches Historisches Museum"
      }
    },
    {
      "type": "museum",
      "id": 4708547016,
      "lat": 52.4986678,
      "lon": 13.3566505,
      "tags": {
        "addr:city": "Berlin",
        "addr:country": "DE",
        "addr:housenumber": "7",
        "addr:postcode": "10783",
        "addr:street": "Bülowstraße",
        "addr:suburb": "Schöneberg",
        "check_date:opening_hours": "2024-03-25",
        "description": "Museum for Urban Contemporary Art",
        "email": "contact@urban-nation.com",
        "fee": "no",
        "image": "img/panagea/pois/Schöneberg_Bülowstraße_7_Urban_Nation_2019.jpg",
        "name": "Urban Nation",
        "opening_hours": "Tu,We 10:00-18:00; Mo off; Th-Su 12:00-20:00",
        "toilets:wheelchair": "yes",
        "tourism": "museum",
        "website": "https://urban-nation.com/",
        "wheelchair": "yes",
        "wikidata": "Q111594318"
      }
    },
    {
      "type": "museum",
      "id": 4725890783,
      "lat": 52.5268086,
      "lon": 13.3953314,
      "tags": {
        "image": "img/panagea/pois/Eingang_Samurai_Museum_Berlin.jpg",
        "addr:country": "DE",
        "addr:housenumber": "68",
        "addr:postcode": "10117",
        "addr:street": "Auguststraße",
        "addr:suburb": "Dahlem",
        "alt_name": "Samurai Art Museum",
        "check_date": "2024-06-09",
        "contact:email": "info@samuraimuseum.de",
        "contact:facebook": "https://www.facebook.com/museumberlin/",
        "contact:instagram": "https://www.instagram.com/samuraimuseumberlin/",
        "contact:phone": "+49 30 62975635",
        "contact:website": "https://samuraimuseum.de/",
        "description": "Peter Janssen Collection. Eine der weltweit bedeutendsten Privatsammlungen mit über 4000 Originalobjekten präsentiert ihre Highlights in Berlin Mitte. Ein Erlebnis für die gesamte Familie!",
        "fee": "yes",
        "level": "0",
        "museum": "history",
        "name": "Samurai Museum Berlin",
        "name:de": "Samurai Museum Berlin",
        "name:en": "Samurai Museum Berlin",
        "opening_hours": "Mo-Su 10:00-19:00",
        "operator": "Samurai Museum Berlin GmbH",
        "operator:type": "private_non_profit",
        "origin": "japanese",
        "payment:cash": "yes",
        "payment:credit_cards": "yes",
        "payment:debit_cards": "yes",
        "start_date": "2017",
        "tourism": "museum",
        "wheelchair": "yes",
        "wikidata": "Q111975442"
      }
    },
    {
      "type": "museum",
      "id": 8413352835,
      "lat": 52.5170316,
      "lon": 13.4012274,
      "tags": {
        "addr:city": "Berlin",
        "addr:country": "DE",
        "addr:postcode": "10178",
        "addr:street": "Schloßplatz",
        "addr:suburb": "Mitte",
        "air_conditioning": "yes",
        "check_date": "2024-07-14",
        "contact:phone": "+49 30 992118989",
        "contact:website": "https://www.humboldtforum.org/",
        "description": "Das Humboldt Forum ist die Museumsplattform im (rekonstruierten) Berliner Schloss",
        "fee": "no",
        "image": "img/panagea/pois/20230729_1510222.jpg",
        "internet_access": "wlan",
        "internet_access:fee": "no",
        "name": "Humboldt Forum",
        "nohousenumber": "yes",
        "opening_hours": "Mo,We-Su 10:30-18:30; Tu off",
        "operator": "Stiftung Humboldt Forum im Berliner Schloss",
        "operator:type": "public",
        "start_date": "2020-12-16",
        "toilets": "yes",
        "toilets:wheelchair": "yes",
        "tourism": "museum",
        "url": "https://youtu.be/66hOhhF-bfs",
        "wheelchair": "yes",
        "wheelchair:website": "https://www.humboldtforum.org/de/barrierefreiheit/",
        "wikidata": "Q20196262",
        "wikipedia": "de:Humboldt Forum"
      }
    },
    {
      "type": "museum",
      "id": 11203063853,
      "lat": 52.5029022,
      "lon": 13.3803524,
      "tags": {
        "email": "kasse@berlinstory-bunker.de",
        "fee": "yes",
        "image": "img/panagea/pois/Berlin_Story_Bunker_im_Anhalter_Hochbunker.jpg",
        "name": "Berlin Story Bunker",
        "opening_hours": "Mo-Su 10:00-19:00",
        "operator": "Berlin Story Bunker GmbH",
        "phone": "+49 30 26555546",
        "tourism": "museum",
        "website": "https://www.berlinstory.de/",
        "wikidata": "Q122705459"
      }
    },
    {
      "type": "museum",
      "id": 11813223472,
      "lat": 52.5179501,
      "lon": 13.3915589,
      "tags": {
        "access": "yes",
        "addr:city": "Berlin",
        "addr:housenumber": "8",
        "addr:postcode": "10117",
        "addr:street": "Unter den Linden",
        "contact:email": "kulturwerk@sbb.spk-berlin.de",
        "contact:instagram": "https://www.instagram.com/stabikulturwerk/",
        "contact:website": "https://stabi-kulturwerk.de/",
        "description": "1.000 Quadratmeter große Ausstellung zur Geschichte der Staatsbibliothek zu Berlin und ihrer Sammlungen.",
        "fee": "no",
        "image": "img/panagea/pois/Stabi_Kulturwerk.jpg",
        "name": "Stabi Kulturwerk",
        "opening_hours": "Tu-Su 10:00-18:00, Th 10:00-20:00; PH,Mo off; May 14,Dec 24,Dec 31 off",
        "operator": "Stiftung Preußischer Kulturbesitz",
        "operator:short": "SPK",
        "operator:type": "public",
        "operator:wikidata": "Q685171",
        "operator:wikipedia": "de:Stiftung Preußischer Kulturbesitz",
        "tourism": "museum",
        "wheelchair": "yes",
        "wikidata": "Q117822507",
        "wikimedia_commons": "Category:Stabi Kulturwerk"
      }
    }
];